spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/lip_projeto
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.security.jwt.secret-key=Hc2bV4r0uUdcKqVg6s4ljxYwXq3EqLzB6sp4fS7vL9o=
spring.security.jwt.expiration-time=600000
spring.security.jwt.refresh-expiration-time=604800000

logging.level.org.hibernate.orm.jdbc.bind=trace

